name: cannon_physics
description: A 3D physics engine for dart (based on cannon.js) that allows users to add physics support to their 3D projects.
version: 0.0.2
homepage: https://github.com/Knightro63/cannon_physics

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

