name: cannon_physics_example
description: Demonstrates how to use the cannon_physics plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cannon_physics:
    path: ../
  vector_math: ^2.1.4
  flutter_gl: ^0.0.21
  three_dart:
    git:
      url: https://github.com/Knightro63/three_dart.git
  three_dart_jsm:
    git:
      url: https://github.com/Knightro63/three_dart_jsm.git
  css:
    git:
      url: https://github.com/Knightro63/css.git
      
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
